In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Data\\medical_disease.csv")

In [3]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,Male,17.5,102,177,161,88,No,No,Medium,No,Healthy
1,69,Male,31.1,118,256,147,92,No,No,High,Yes,Pre-Diabetes
2,61,Female,31.3,114,206,193,74,Yes,No,Medium,No,Healthy
3,47,Female,23.9,105,162,253,68,No,No,Low,No,Healthy
4,47,Male,28.3,148,121,280,84,No,Yes,High,No,Healthy
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,Male,27.1,177,183,268,59,No,No,High,No,Hypertension
9996,84,Male,29.2,142,215,145,77,No,Yes,High,Yes,Hypertension
9997,41,Male,22.8,177,265,133,71,No,No,Medium,Yes,Hypertension
9998,55,Male,29.0,126,241,298,57,No,No,Medium,Yes,Pre-Diabetes
9999,59,Male,32.2,151,162,225,93,No,No,High,Yes,Pre-Diabetes

In [4]:
print("Shape of Dataset:", df.shape)

Shape of Dataset: (10000, 12)

In [5]:
print(df.columns)

Index(['Age', 'Gender', 'BMI', 'BloodPressure', 'GlucoseLevel', 'Cholesterol',
       'HeartRate', 'Smoking', 'Alcohol', 'PhysicalActivity', 'FamilyHistory',
       'Disease'],
      dtype='object')

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               10000 non-null  int64
 1   Gender            10000 non-null  object
 2   BMI               10000 non-null  float64
 3   BloodPressure     10000 non-null  int64
 4   GlucoseLevel      10000 non-null  int64
 5   Cholesterol       10000 non-null  int64
 6   HeartRate         10000 non-null  int64
 7   Smoking           10000 non-null  object
 8   Alcohol           10000 non-null  object
 9   PhysicalActivity  10000 non-null  object
 10  FamilyHistory     10000 non-null  object
 11  Disease           10000 non-null  object
dtypes: float64(1), int64(5), object(6)
memory usage: 937.6+ KB
None

In [7]:
print(df.isnull().sum())

Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [8]:
print( df.duplicated().sum())

0

In [9]:
df = df.drop_duplicates()

In [10]:
print( df.duplicated().sum())

0

In [11]:
for col in df.columns:
    print("\nColumn:", col)
    print(df[col].unique())

Column: Age
[23 69 61 47 75 64 31 24 53 83 67 68 66 70 52 26 74 48 51 42 30 80 44 73
 54 33 55 77 22 36 60 29 41 63 49 20 28 79 82 45 39 78 71 40 62 81 38 43
 37 34 27 18 65 56 25 58 32 84 21 46 72 19 35 57 59 50 76]

Column: Gender
['Male' 'Female']

Column: BMI
[17.5 31.1 31.3 23.9 28.3 25.  27.1 20.8 28.8 18.6 17.8 25.5 27.2 23.1
 34.5 26.7 27.  26.9 30.5 28.6 28.  29.3 18.  25.7 25.1 26.1 20.4 26.
 20.  27.7 27.6 19.4 24.3 30.  23.  19.2 18.4 26.5 28.5 28.7 25.9 24.8
 21.2 24.  20.1 22.2 26.4 39.8 19.9 25.4 19.6 24.4 29.8 24.1 19.7 26.3
 24.9 18.3 28.4 22.9 29.4 31.9 25.2 21.4 24.6 23.5 28.2 28.1 22.5 28.9
 17.1 31.7 27.8 20.6 29.1 23.8 29.7 17.9 21.3 16.7 22.  32.8 35.3 19.
 23.4 32.5 22.6 27.3 23.2 34.8 25.8 32.9 30.8 25.6 19.5 31.5 27.9 21.6
 23.7 34.3 35.  21.8 29.9 31.8 26.6 19.1 26.8 29.5 22.4 16.4 25.3 30.7
 29.6 30.6 16.  33.8 37.1 18.1 24.5 30.9 20.2 30.3 30.1 27.4 32.2 17.7
 23.6 33.3 24.7 32.6 18.9 22.3 22.8 31.6 18.8 35.4 18.7 35.6 20.7 27.5
 16.1 36.6 20.9 34.1 20.3 39.7 21.9 17.4 36.4 21.1 22.7 22.1 36.1 21.5
 23.3 30.2 37.8 18.2 21.7 26.2 16.5 38.1 33.9 33.4 20.5 34.9 31.4 19.8
 29.  34.  24.2 31.2 33.2 33.6 35.8 21.  33.7 29.2 32.  37.7 33.5 30.4
 35.5 16.9 32.1 31.  32.4 19.3 32.3 33.  40.1 18.5 34.7 17.2 16.6 17.6
 32.7 34.4 35.7 36.8 35.2 33.1 36.  17.  36.2 17.3 39.6 36.9 40.4 16.3
 34.6 36.7 16.8 38.4 34.2 37.5 44.7 36.5 38.7 35.1 38.9 35.9 39.2 37.2
 36.3 37.4 39.3 16.2 40.  37.  37.9 38.8 38.  38.6 39.  37.3 40.2 39.5]

Column: BloodPressure
[102 118 114 105 148  90 125 101 145 158 132 130 108 124 174  93 161 104
 100 115 167 172 153 103 176  96 160  98 120 139 154 112 119 107 106 142
 166  91  95 138 152 121 147 165 159 162 178 143 126 122 164 116 135 131
  97 117 170 180 175 149 146 144  99 109 168  92 155 133 141 128 137 173
 163 110 127 136 157 171 179 134 156 140  94 123 177 151 129 111 169 113
 150]

Column: GlucoseLevel
[177 256 206 162 121 136  85 102  76 169  78 104 215 141 110  81 113  93
  86 210  96 268 172 156 254 234 158 275 181 219 274 222 194 199 208 276
 217 133  74 235 157 267  77 226 264 245 253 252 214 142 227  89 131 114
 190 161 203 192 213  82 242  75 179 239 231 196 107 271 143 229 200 236
 178 243 106  80 174 163 204 145  70 220  98 198 230 191 218 129 108 273
 269 167 205 103 137 251  72  88 101 257 115 149  83 241 207 260 233 140
 223 248 216 221 128  94 202 159 180 270 139 250 237  92 262 201 144 105
 211 117 280 232 119 164 224 197 279 123 165 160 166 263 150 100 116  87
 148 184 212 189 249 183 171  99 152 244  73 187 153  95 132 151 240 265
 193 118 246 186 138 176 228 147 130  91 272 135  90 112 247  84 154  71
 188 277 126 266 259 124  97  79 134 278 238 209 225 185 111 109 125 173
 120 155 122 255 195 258 175 168 127 182 146 170 261]

Column: Cholesterol
[161 147 193 253 280 126 212 308 285 312 138 256 230 215 307 213 250 216
 247 315 283 166 294 225 237 143 209 180 137 291 145 264 269 243 288 142
 123 290 156 179 258 227 160 224 305 232 188 221 266 201 292 260 229 165
 296 131 129 277 125 222 157 173 195 132 158 176 144 298 263 181 208 274
 313 223 170 282 265 279 231 241 192 276 124 204 303 168 220 141 299 273
 148 251 121 130 153 184 310 267 122 246 293 203 135 151 268 262 316 205
 278 183 199 162 152 206 140 257 275 207 236 301 238 194 159 317 178 200
 154 318 240 182 217 175 163 271 281 120 309 210 169 196 234 289 248 311
 139 244 259 164 197 306 255 127 167 189 172 198 155 186 304 235 218 252
 214 134 171 239 245 174 233 286 149 261 202 219 254 272 190 297 319 133
 300 191 228 249 284 150 270 287 314 295 211 146 226 177 185 320 302 136
 242 187 128]

Column: HeartRate
[ 88  92  74  68  84  59  71 107  97  72  58  76  93  57 103 104  89  64
  69  81 109  99  62  87  90  63  66 105  56  86 102  94  79  61 106  73
  77  95  60  83  55  65 100 110  98 101  70  75  67  80  91  85 108  82
  96  78]

Column: Smoking
['No' 'Yes']

Column: Alcohol
['No' 'Yes']

Column: PhysicalActivity
['Medium' 'High' 'Low']

Column: FamilyHistory
['No' 'Yes']

Column: Disease
['Healthy' 'Pre-Diabetes' 'Hypertension' 'Heart Disease' 'Diabetes']

In [13]:

Gender_list = df['Gender'].unique().tolist()
Gender_dict = {Gender: i for i, Gender in enumerate(Gender_list)}
print(Gender_dict)
df['Gender'] = df['Gender'].map(Gender_dict)


df['Smoking'] = df['Smoking'].map({'No':0,'Yes':1}).astype(int)

df['Alcohol'] = df['Alcohol'].map({ 'No':0,'Yes':1})

df['FamilyHistory'] = df['FamilyHistory'].map({'No':0,'Yes':1})

df['PhysicalActivity'] = df['PhysicalActivity'].map({'Medium':2, 'High':3, 'Low':1})

df['Disease'] = df['Disease'].map({'Healthy':1, 'Pre-Diabetes':2, 'Hypertension':3, 'Heart Disease':4, 'Diabetes':5})

{'Male': 0, 'Female': 1}

In [15]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,0,17.5,102,177,161,88,0,0,2,0,1
1,69,0,31.1,118,256,147,92,0,0,3,1,2
2,61,1,31.3,114,206,193,74,1,0,2,0,1
3,47,1,23.9,105,162,253,68,0,0,1,0,1
4,47,0,28.3,148,121,280,84,0,1,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,0,27.1,177,183,268,59,0,0,3,0,3
9996,84,0,29.2,142,215,145,77,0,1,3,1,3
9997,41,0,22.8,177,265,133,71,0,0,2,1,3
9998,55,0,29.0,126,241,298,57,0,0,2,1,2
9999,59,0,32.2,151,162,225,93,0,0,3,1,2

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               10000 non-null  int64
 1   Gender            10000 non-null  int64
 2   BMI               10000 non-null  float64
 3   BloodPressure     10000 non-null  int64
 4   GlucoseLevel      10000 non-null  int64
 5   Cholesterol       10000 non-null  int64
 6   HeartRate         10000 non-null  int64
 7   Smoking           10000 non-null  int64
 8   Alcohol           10000 non-null  int64
 9   PhysicalActivity  10000 non-null  int64
 10  FamilyHistory     10000 non-null  int64
 11  Disease           10000 non-null  int64
dtypes: float64(1), int64(11)
memory usage: 937.6 KB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Age                 0
Gender              0
BMI                 0
BloodPressure       0
GlucoseLevel        0
Cholesterol         0
HeartRate           0
Smoking             0
Alcohol             0
PhysicalActivity    0
FamilyHistory       0
Disease             0
dtype: int64

In [ ]:
df.to_csv("medical_disease_cleaned.csv",index=False)

In [ ]:
x = df.drop('Disease', axis=1)
y = df['Disease']

In [ ]:
x

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
0,23,0,17.5,102,177,161,88,0,0,2,0
1,69,0,31.1,118,256,147,92,0,0,3,1
2,61,1,31.3,114,206,193,74,1,0,2,0
3,47,1,23.9,105,162,253,68,0,0,1,0
4,47,0,28.3,148,121,280,84,0,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,49,0,27.1,177,183,268,59,0,0,3,0
9996,84,0,29.2,142,215,145,77,0,1,3,1
9997,41,0,22.8,177,265,133,71,0,0,2,1
9998,55,0,29.0,126,241,298,57,0,0,2,1
9999,59,0,32.2,151,162,225,93,0,0,3,1

In [ ]:
y

0       1
1       2
2       1
3       1
4       1
       ..
9995    3
9996    3
9997    3
9998    2
9999    2
Name: Disease, Length: 10000, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

In [ ]:
x_train

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
9254,76,0,29.6,134,266,318,101,1,0,2,1
1561,35,1,29.3,96,220,300,58,0,0,1,0
1670,69,0,29.6,164,149,229,98,0,0,1,0
6087,47,0,29.0,159,250,258,109,0,1,2,0
6669,42,0,23.4,107,224,300,82,1,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...
5734,61,1,30.2,175,147,167,102,0,1,1,0
5191,79,1,20.5,150,225,142,84,0,0,2,1
5390,30,0,27.6,119,101,129,110,0,0,2,0
860,82,0,30.7,108,143,231,102,1,0,1,1
7270,38,0,17.3,176,89,284,66,0,1,3,1

In [ ]:
x_test

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
6252,36,0,23.5,122,156,146,99,0,1,2,1
4684,52,1,23.0,147,137,273,107,0,0,3,0
1731,78,0,26.3,118,128,125,55,0,0,2,1
4742,46,0,22.6,161,211,147,59,0,0,1,0
4521,64,1,27.2,126,261,162,108,1,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...
6412,23,1,25.5,114,204,220,99,0,0,1,0
8285,20,0,32.3,131,257,287,77,0,0,1,0
7853,53,1,26.8,180,240,306,94,0,0,3,0
1095,23,1,35.2,118,148,292,100,0,0,1,0
6929,68,1,16.5,105,117,307,62,0,0,2,0

In [ ]:
y_train

9254    3
1561    1
1670    1
6087    1
6669    1
       ..
5734    2
5191    1
5390    1
860     3
7270    3
Name: Disease, Length: 8000, dtype: int64

In [ ]:
y_test

6252    1
4684    1
1731    1
4742    1
4521    3
       ..
6412    1
8285    1
7853    3
1095    1
6929    1
Name: Disease, Length: 2000, dtype: int64

In [ ]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(8000, 11) (2000, 11) (8000,) (2000,)

In [ ]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,0,17.5,102,177,161,88,0,0,2,0,1
1,69,0,31.1,118,256,147,92,0,0,3,1,2
2,61,1,31.3,114,206,193,74,1,0,2,0,1
3,47,1,23.9,105,162,253,68,0,0,1,0,1
4,47,0,28.3,148,121,280,84,0,1,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,0,27.1,177,183,268,59,0,0,3,0,3
9996,84,0,29.2,142,215,145,77,0,1,3,1,3
9997,41,0,22.8,177,265,133,71,0,0,2,1,3
9998,55,0,29.0,126,241,298,57,0,0,2,1,2
9999,59,0,32.2,151,162,225,93,0,0,3,1,2

# SVM (SVR)

In [ ]:
from sklearn.svm import SVR
sv=SVR()
sv.fit(x_train,y_train)

SVR()

In [ ]:
print('SVR test score:-',sv.score(x_test,y_test))
print('SVR train score:-',sv.score(x_train,y_train))

SVR test score:- 0.21312438447786386
SVR train score:- 0.19048329546751752

# SVM (SVC)

In [ ]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)

SVC()

In [ ]:
print('SVC test score:-',sv.score(x_test,y_test))
print('SVC train score:-',sv.score(x_train,y_train))

SVC test score:- 0.6395
SVC train score:- 0.63125

# LinearRegression

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
print('LinearRegression test score:-',lr.score(x_test,y_test))
print('LinearRegression train score:-',lr.score(x_train,y_train))

LinearRegression test score:- 0.41233703387196996
LinearRegression train score:- 0.3825630863031215

# LogisticRegression

In [ ]:
from sklearn.linear_model import LogisticRegression
log =LogisticRegression()
log.fit(x_train,y_train)

c:\Users\KRISHAN\Downloads\data science\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
print("LogisticRegression training",log.score(x_train,y_train))
print("LogisticRegression testing",log.score(x_test,y_test))

LogisticRegression training 0.631125
LogisticRegression testing 0.642

# DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
print('DecisionTreeClassifier test score:-',dt.score(x_test,y_test))
print('DecisionTreeClassifier train score:-',dt.score(x_train,y_train))

DecisionTreeClassifier test score:- 0.647
DecisionTreeClassifier train score:- 1.0

# with parameters

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier(criterion='entropy', min_samples_split=3, min_samples_leaf=2, random_state=42)
dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=3, random_state=42)

In [ ]:
print('DecisionTreeClassifier test score:-',dt.score(x_test,y_test))
print('DecisionTreeClassifier train score:-',dt.score(x_train,y_train))

DecisionTreeClassifier test score:- 0.656
DecisionTreeClassifier train score:- 0.94275

# DecisionTreeRegressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt =DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [ ]:
print('DecisionTreeRegressor test score:-',dt.score(x_test,y_test))
print('DecisionTreeRegressor train score:-',dt.score(x_train,y_train))

DecisionTreeRegressor test score:- 0.25682578917935406
DecisionTreeRegressor train score:- 1.0

# with parameters

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(criterion='squared_error',min_samples_split=3,min_samples_leaf=2,random_state=42)
dt.fit(x_train, y_train)

DecisionTreeRegressor(min_samples_leaf=2, min_samples_split=3, random_state=42)

In [ ]:
print("DecisionTreeRegressor Test Score:", dt.score(x_test, y_test))
print("DecisionTreeRegressor Train Score:", dt.score(x_train, y_train))

DecisionTreeRegressor Test Score: 0.33640469324281963
DecisionTreeRegressor Train Score: 0.9558519566074887